server:
  port: 18000
spring:
  profiles:
    include: dubbo
dubbo:
  scan:
    #扫描Dubbo服务的路径
    base-packages: com.want.provider.dubbo.api
  cloud:
    #订阅的服务
    subscribed-services: ''
  protocols:
    dubbo:
      #dubbo 端口
      port: 38000